// Auto-generated by hub-codegen
// Do not edit manually

/** Known build system types */
export type BuildSystemKind = "cargo" | "cabal" | "node" | "unknown";

/** Status information */
export interface HyperforgeEventStatus {
  type: 'status';
  description: string;
  version: string;
}

/** General info message */
export interface HyperforgeEventInfo {
  type: 'info';
  message: string;
}

/** Error message */
export interface HyperforgeEventError {
  type: 'error';
  message: string;
}

/** Repository information */
export interface HyperforgeEventRepo {
  type: 'repo';
  description: string | null;
  mirrors: string[];
  name: string;
  origin: string;
  protected: boolean;
  stagedForDeletion: boolean;
  visibility: string;
}

/** Sync diff result - repo operation */
export interface HyperforgeEventSyncOp {
  type: 'sync_op';
  forge: string;
  operation: string;
  repoName: string;
}

/** Sync summary */
export interface HyperforgeEventSyncSummary {
  type: 'sync_summary';
  forge: string;
  inSync: number;
  toCreate: number;
  toDelete: number;
  toUpdate: number;
  total: number;
}

/** Per-repo check result (branch + clean status) */
export interface HyperforgeEventRepoCheck {
  type: 'repo_check';
  branch: string;
  expectedBranch: string;
  isClean: boolean;
  onCorrectBranch: boolean;
  path: string;
  repoName: string;
}

/** Per-repo push result */
export interface HyperforgeEventRepoPush {
  type: 'repo_push';
  error: string | null;
  forge: string;
  path: string;
  repoName: string;
  success: boolean;
}

/** Workspace-level summary */
export interface HyperforgeEventWorkspaceSummary {
  type: 'workspace_summary';
  cleanRepos: number | null;
  configuredRepos: number;
  dirtyRepos: number | null;
  pushFailed: number | null;
  pushSuccess: number | null;
  totalRepos: number;
  unconfiguredRepos: number;
  validationPassed: boolean | null;
  wrongBranchRepos: number | null;
}

/** Result of workspace unify (native workspace file generation) */
export interface HyperforgeEventUnifyResult {
  type: 'unify_result';
  action: string;
  filePath: string;
  language: string;
}

/** Dependency version mismatch between pinned and local */
export interface HyperforgeEventDepMismatch {
  type: 'dep_mismatch';
  dependency: string;
  localVersion: string;
  pinnedVersion: string;
  repo: string;
}

/** Validation step result */
export interface HyperforgeEventValidateStep {
  type: 'validate_step';
  durationMs: number;
  repoName: string;
  status: string;
  step: string;
}

/** Validation summary */
export interface HyperforgeEventValidateSummary {
  type: 'validate_summary';
  durationMs: number;
  failed: number;
  passed: number;
  skipped: number;
  total: number;
}

/** Per-repo move step result */
export interface HyperforgeEventRepoMove {
  type: 'repo_move';
  message: string;
  repoName: string;
  step: string;
  success: boolean;
}

/** Result of workspace exec command for a single repo */
export interface HyperforgeEventExecResult {
  type: 'exec_result';
  exitCode: number;
  repoName: string;
  stderr: string;
  stdout: string;
}

/** Package registry diff — local vs published version */
export interface HyperforgeEventPackageDiff {
  type: 'package_diff';
  buildSystem: BuildSystemKind;
  /** Files that differ between local and published artifact. */
  changedFiles: unknown[] | null;
  localVersion: string;
  packageName: string;
  publishedVersion: string | null;
  registry: PackageRegistry;
  status: PackageStatus;
}

/** Per-package publish step result */
export interface HyperforgeEventPublishStep {
  type: 'publish_step';
  action: PublishActionKind;
  error: string | null;
  packageName: string;
  registry: PackageRegistry;
  success: boolean;
  version: string;
}

/** Summary of a publish run */
export interface HyperforgeEventPublishSummary {
  type: 'publish_summary';
  autoBumped: number;
  failed: number;
  published: number;
  skipped: number;
  tagsCreated: number;
  total: number;
}

/** Hyperforge event types */
export type HyperforgeEvent = HyperforgeEventStatus | HyperforgeEventInfo | HyperforgeEventError | HyperforgeEventRepo | HyperforgeEventSyncOp | HyperforgeEventSyncSummary | HyperforgeEventRepoCheck | HyperforgeEventRepoPush | HyperforgeEventWorkspaceSummary | HyperforgeEventUnifyResult | HyperforgeEventDepMismatch | HyperforgeEventValidateStep | HyperforgeEventValidateSummary | HyperforgeEventRepoMove | HyperforgeEventExecResult | HyperforgeEventPackageDiff | HyperforgeEventPublishStep | HyperforgeEventPublishSummary;

export function isHyperforgeEventStatus(e: HyperforgeEvent): e is HyperforgeEventStatus { return e.type === 'status'; }
export function isHyperforgeEventInfo(e: HyperforgeEvent): e is HyperforgeEventInfo { return e.type === 'info'; }
export function isHyperforgeEventError(e: HyperforgeEvent): e is HyperforgeEventError { return e.type === 'error'; }
export function isHyperforgeEventRepo(e: HyperforgeEvent): e is HyperforgeEventRepo { return e.type === 'repo'; }
export function isHyperforgeEventSyncOp(e: HyperforgeEvent): e is HyperforgeEventSyncOp { return e.type === 'sync_op'; }
export function isHyperforgeEventSyncSummary(e: HyperforgeEvent): e is HyperforgeEventSyncSummary { return e.type === 'sync_summary'; }
export function isHyperforgeEventRepoCheck(e: HyperforgeEvent): e is HyperforgeEventRepoCheck { return e.type === 'repo_check'; }
export function isHyperforgeEventRepoPush(e: HyperforgeEvent): e is HyperforgeEventRepoPush { return e.type === 'repo_push'; }
export function isHyperforgeEventWorkspaceSummary(e: HyperforgeEvent): e is HyperforgeEventWorkspaceSummary { return e.type === 'workspace_summary'; }
export function isHyperforgeEventUnifyResult(e: HyperforgeEvent): e is HyperforgeEventUnifyResult { return e.type === 'unify_result'; }
export function isHyperforgeEventDepMismatch(e: HyperforgeEvent): e is HyperforgeEventDepMismatch { return e.type === 'dep_mismatch'; }
export function isHyperforgeEventValidateStep(e: HyperforgeEvent): e is HyperforgeEventValidateStep { return e.type === 'validate_step'; }
export function isHyperforgeEventValidateSummary(e: HyperforgeEvent): e is HyperforgeEventValidateSummary { return e.type === 'validate_summary'; }
export function isHyperforgeEventRepoMove(e: HyperforgeEvent): e is HyperforgeEventRepoMove { return e.type === 'repo_move'; }
export function isHyperforgeEventExecResult(e: HyperforgeEvent): e is HyperforgeEventExecResult { return e.type === 'exec_result'; }
export function isHyperforgeEventPackageDiff(e: HyperforgeEvent): e is HyperforgeEventPackageDiff { return e.type === 'package_diff'; }
export function isHyperforgeEventPublishStep(e: HyperforgeEvent): e is HyperforgeEventPublishStep { return e.type === 'publish_step'; }
export function isHyperforgeEventPublishSummary(e: HyperforgeEvent): e is HyperforgeEventPublishSummary { return e.type === 'publish_summary'; }

/** Package registry identifier */
export type PackageRegistry = "crates_io" | "hackage" | "npm";

/** Package status relative to its registry */
export type PackageStatus = "ahead" | "up_to_date" | "unpublished" | "stale" | "drifted";

/** Action taken or planned during publish */
export type PublishActionKind = "publish" | "auto_bump" | "initial_publish" | "skip" | "tag" | "failed";
