// Auto-generated by hub-codegen
// Do not edit manually

/** Echo response */
export interface EchoEventEcho {
  type: 'echo';
  /** Number of times repeated */
  count: number;
  /** The echoed message */
  message: string;
}

/** Pong response (from ping) */
export interface EchoEventPong {
  type: 'pong';
}

/** Events from echo operations */
export type EchoEvent = EchoEventEcho | EchoEventPong;

export function isEchoEventEcho(e: EchoEvent): e is EchoEventEcho { return e.type === 'echo'; }
export function isEchoEventPong(e: EchoEvent): e is EchoEventPong { return e.type === 'pong'; }
