// Auto-generated by hub-codegen
// Do not edit manually

/** Template rendered successfully */
export interface MustacheEventRendered {
  type: 'rendered';
  /** The rendered output */
  output: string;
}

/** Template registered successfully */
export interface MustacheEventRegistered {
  type: 'registered';
  /** Template info */
  template: TemplateInfo;
}

/** Template retrieved */
export interface MustacheEventTemplate {
  type: 'template';
  /** The template content */
  template: string;
}

/** Template not found */
export interface MustacheEventNotFound {
  type: 'not_found';
  /** Description of what was not found */
  message: string;
}

/** List of templates */
export interface MustacheEventTemplates {
  type: 'templates';
  /** The templates */
  templates: TemplateInfo[];
}

/** Template deleted */
export interface MustacheEventDeleted {
  type: 'deleted';
  /** Number of templates deleted */
  count: number;
}

/** Error occurred */
export interface MustacheEventError {
  type: 'error';
  /** Error message */
  message: string;
}

/** Events from mustache operations */
export type MustacheEvent = MustacheEventRendered | MustacheEventRegistered | MustacheEventTemplate | MustacheEventNotFound | MustacheEventTemplates | MustacheEventDeleted | MustacheEventError;

export function isMustacheEventRendered(e: MustacheEvent): e is MustacheEventRendered { return e.type === 'rendered'; }
export function isMustacheEventRegistered(e: MustacheEvent): e is MustacheEventRegistered { return e.type === 'registered'; }
export function isMustacheEventTemplate(e: MustacheEvent): e is MustacheEventTemplate { return e.type === 'template'; }
export function isMustacheEventNotFound(e: MustacheEvent): e is MustacheEventNotFound { return e.type === 'not_found'; }
export function isMustacheEventTemplates(e: MustacheEvent): e is MustacheEventTemplates { return e.type === 'templates'; }
export function isMustacheEventDeleted(e: MustacheEvent): e is MustacheEventDeleted { return e.type === 'deleted'; }
export function isMustacheEventError(e: MustacheEvent): e is MustacheEventError { return e.type === 'error'; }

/** Information about a registered template */
export interface TemplateInfo {
  /** When the template was created (Unix timestamp) */
  createdAt: number;
  /** Unique template ID */
  id: string;
  /** Method this template is for */
  method: string;
  /** Template name (e.g., "default", "compact", "verbose") */
  name: string;
  /** Plugin that owns this template */
  pluginId: string;
  /** When the template was last updated (Unix timestamp) */
  updatedAt: number;
}
