// Auto-generated by hub-codegen
// Do not edit manually

/** A pending approval request */
export interface ApprovalRequest {
  createdAt: number;
  id: string;
  input: unknown;
  resolvedAt?: number | null;
  responseMessage?: string | null;
  sessionId: string;
  status: ApprovalStatus;
  toolName: string;
  toolUseId: string;
}

/** Status of an approval request */
export type ApprovalStatus = "pending" | "approved" | "denied" | "timed_out";

export interface ConfigureResultOk {
  type: 'ok';
  mcpConfig: unknown;
}

export interface ConfigureResultError {
  type: 'error';
  message: string;
}

export type ConfigureResult = ConfigureResultOk | ConfigureResultError;

export function isConfigureResultOk(e: ConfigureResult): e is ConfigureResultOk { return e.type === 'ok'; }
export function isConfigureResultError(e: ConfigureResult): e is ConfigureResultError { return e.type === 'error'; }

export interface PendingResultOk {
  type: 'ok';
  approvals: ApprovalRequest[];
}

export interface PendingResultError {
  type: 'error';
  message: string;
}

export type PendingResult = PendingResultOk | PendingResultError;

export function isPendingResultOk(e: PendingResult): e is PendingResultOk { return e.type === 'ok'; }
export function isPendingResultError(e: PendingResult): e is PendingResultError { return e.type === 'error'; }

export interface RespondResultOk {
  type: 'ok';
  approvalId: string;
}

export interface RespondResultError {
  type: 'error';
  message: string;
}

export type RespondResult = RespondResultOk | RespondResultError;

export function isRespondResultOk(e: RespondResult): e is RespondResultOk { return e.type === 'ok'; }
export function isRespondResultError(e: RespondResult): e is RespondResultError { return e.type === 'error'; }

// === Stub Types (referenced but not defined in schema) ===

/** Stub type - definition missing from IR */
export type String = unknown;
