// Auto-generated by hub-codegen
// Do not edit manually

/** Events emitted by the confirm method */
export type ConfirmEvent = never;

/** Events emitted by the delete method */
export type DeleteEvent = never;

/** Events emitted by the wizard method */
export type WizardEvent = never;
