// Auto-generated by hub-codegen
// Do not edit manually

/** A changelog entry documenting a plexus hash transition */
export interface ChangelogEntry {
  /** Who/what added this entry */
  author?: string | null;
  /** Unix timestamp when this entry was added */
  createdAt: number;
  /** Detailed list of changes (bullet points) */
  details?: string[];
  /** The plexus_hash this entry documents */
  hash: string;
  /** The previous hash this transitioned from (None for initial entry) */
  previousHash?: string | null;
  /** Reference to a queue item this changelog completes */
  queueId?: string | null;
  /** Short summary of changes (one line) */
  summary: string;
}

/** Entry was added */
export interface ChangelogEventEntryAdded {
  type: 'entry_added';
  entry: ChangelogEntry;
}

/** List of entries */
export interface ChangelogEventEntries {
  type: 'entries';
  entries: ChangelogEntry[];
}

/** Current state check result */
export interface ChangelogEventStatus {
  type: 'status';
  currentHash: string;
  entry: ChangelogEntry | null;
  isDocumented: boolean;
  previousHash: string | null;
}

/** Startup check result */
export interface ChangelogEventStartupCheck {
  type: 'startup_check';
  currentHash: string;
  hashChanged: boolean;
  isDocumented: boolean;
  message: string;
  previousHash: string | null;
}

/** Queue item was added */
export interface ChangelogEventQueueAdded {
  type: 'queue_added';
  entry: QueueEntry;
}

/** Queue item was updated (e.g., marked complete) */
export interface ChangelogEventQueueUpdated {
  type: 'queue_updated';
  entry: QueueEntry;
}

/** List of queue items */
export interface ChangelogEventQueueEntries {
  type: 'queue_entries';
  entries: QueueEntry[];
}

/** Single queue item */
export interface ChangelogEventQueueItem {
  type: 'queue_item';
  entry: QueueEntry | null;
}

/** Events emitted by changelog operations */
export type ChangelogEvent = ChangelogEventEntryAdded | ChangelogEventEntries | ChangelogEventStatus | ChangelogEventStartupCheck | ChangelogEventQueueAdded | ChangelogEventQueueUpdated | ChangelogEventQueueEntries | ChangelogEventQueueItem;

export function isChangelogEventEntryAdded(e: ChangelogEvent): e is ChangelogEventEntryAdded { return e.type === 'entry_added'; }
export function isChangelogEventEntries(e: ChangelogEvent): e is ChangelogEventEntries { return e.type === 'entries'; }
export function isChangelogEventStatus(e: ChangelogEvent): e is ChangelogEventStatus { return e.type === 'status'; }
export function isChangelogEventStartupCheck(e: ChangelogEvent): e is ChangelogEventStartupCheck { return e.type === 'startup_check'; }
export function isChangelogEventQueueAdded(e: ChangelogEvent): e is ChangelogEventQueueAdded { return e.type === 'queue_added'; }
export function isChangelogEventQueueUpdated(e: ChangelogEvent): e is ChangelogEventQueueUpdated { return e.type === 'queue_updated'; }
export function isChangelogEventQueueEntries(e: ChangelogEvent): e is ChangelogEventQueueEntries { return e.type === 'queue_entries'; }
export function isChangelogEventQueueItem(e: ChangelogEvent): e is ChangelogEventQueueItem { return e.type === 'queue_item'; }

/** A queued change - a planned modification that systems should implement */
export interface QueueEntry {
  /** Unix timestamp when this was completed */
  completedAt?: number | null;
  /** The hash where this change was implemented (set when completed) */
  completedHash?: string | null;
  /** Unix timestamp when this was queued */
  createdAt: number;
  /** Description of the planned change */
  description: string;
  /** Unique identifier for this queue item */
  id: string;
  /** Current status of the queue item */
  status: QueueStatus;
  /** Tags to identify which systems this change affects (e.g., "frontend", "api", "breaking") */
  tags?: string[];
}

/** Status of a queued change */
export type QueueStatus = "pending" | "completed";
