// Auto-generated by hub-codegen
// Do not edit manually

/** Type of celestial body */
export type BodyType = "star" | "planet" | "dwarf_planet" | "moon";

/** Information about a celestial body */
export interface SolarEventBody {
  type: 'body';
  bodyType: BodyType;
  massKg: number;
  name: string;
  orbitalPeriodDays: number | null;
  parent: string | null;
  radiusKm: number;
}

/** System overview */
export interface SolarEventSystem {
  type: 'system';
  moonCount: number;
  planetCount: number;
  star: string;
  totalBodies: number;
}

/** Events from solar system observations */
export type SolarEvent = SolarEventBody | SolarEventSystem;

export function isSolarEventBody(e: SolarEvent): e is SolarEventBody { return e.type === 'body'; }
export function isSolarEventSystem(e: SolarEvent): e is SolarEventSystem { return e.type === 'system'; }
