export type { IR, TypeDef, TypeRef, TypeKind, FieldDef, VariantDef, MethodIR } from './types'
export { buildIR } from './build'
export { snakeToCamel, camelToSnake, wireToDisplay, displayToWire } from './names'
export { schemaToTypeRef, extractParamFields, extractVariant, inferTypeKind } from './extract'
export { extractDefs, resolveRef, inlineRefs } from './refs'
