// Auto-generated by hub-codegen
// Do not edit manually

/** Backend connection information */
export interface BackendInfo {
  /** Timestamp when created (Unix seconds) */
  createdAt: number;
  /** Optional description */
  description?: string | null;
  /** Host address */
  host: string;
  /** Unique identifier (UUID) */
  id: string;
  /** Whether this backend is active */
  isActive: boolean;
  /** Timestamp when last seen (Unix seconds, for health checks) */
  lastSeen?: number | null;
  /** JSON metadata (extensibility) */
  metadata?: string | null;
  /** Human-readable name (unique) */
  name: string;
  /** Optional routing namespace */
  namespace?: string | null;
  /** Port number */
  port: number;
  /** Protocol (ws or wss) */
  protocol: string;
  /** Timestamp when registered (Unix seconds) */
  registeredAt: number;
  /** Source of registration */
  source: BackendSource;
  /** Timestamp when last updated (Unix seconds) */
  updatedAt: number;
  /** Plexus version (from hash) */
  version?: string | null;
}

/** Source of a backend registration */
export type BackendSource = "auto" | "file" | "manual" | "env";

/** Backend was registered */
export interface RegistryEventBackendRegistered {
  type: 'backend_registered';
  backend: BackendInfo;
}

/** Backend was updated */
export interface RegistryEventBackendUpdated {
  type: 'backend_updated';
  backend: BackendInfo;
}

/** Backend was deleted */
export interface RegistryEventBackendDeleted {
  type: 'backend_deleted';
  name: string;
}

/** List of backends */
export interface RegistryEventBackends {
  type: 'backends';
  backends: BackendInfo[];
}

/** Single backend info */
export interface RegistryEventBackend {
  type: 'backend';
  backend: BackendInfo | null;
}

/** Ping response */
export interface RegistryEventPing {
  type: 'ping';
  message: string;
  name: string;
  success: boolean;
}

/** Config reloaded */
export interface RegistryEventReloaded {
  type: 'reloaded';
  count: number;
}

/** Error occurred */
export interface RegistryEventError {
  type: 'error';
  message: string;
}

/** Events emitted by registry methods */
export type RegistryEvent = RegistryEventBackendRegistered | RegistryEventBackendUpdated | RegistryEventBackendDeleted | RegistryEventBackends | RegistryEventBackend | RegistryEventPing | RegistryEventReloaded | RegistryEventError;

export function isRegistryEventBackendRegistered(e: RegistryEvent): e is RegistryEventBackendRegistered { return e.type === 'backend_registered'; }
export function isRegistryEventBackendUpdated(e: RegistryEvent): e is RegistryEventBackendUpdated { return e.type === 'backend_updated'; }
export function isRegistryEventBackendDeleted(e: RegistryEvent): e is RegistryEventBackendDeleted { return e.type === 'backend_deleted'; }
export function isRegistryEventBackends(e: RegistryEvent): e is RegistryEventBackends { return e.type === 'backends'; }
export function isRegistryEventBackend(e: RegistryEvent): e is RegistryEventBackend { return e.type === 'backend'; }
export function isRegistryEventPing(e: RegistryEvent): e is RegistryEventPing { return e.type === 'ping'; }
export function isRegistryEventReloaded(e: RegistryEvent): e is RegistryEventReloaded { return e.type === 'reloaded'; }
export function isRegistryEventError(e: RegistryEvent): e is RegistryEventError { return e.type === 'error'; }
