// Auto-generated by hub-codegen
// Do not edit manually

/** Standard output line */
export interface BashEventStdout {
  type: 'stdout';
  line: string;
}

/** Standard error line */
export interface BashEventStderr {
  type: 'stderr';
  line: string;
}

/** Exit code when process completes */
export interface BashEventExit {
  type: 'exit';
  code: number;
}

/** Stream events from bash command execution */
export type BashEvent = BashEventStdout | BashEventStderr | BashEventExit;

export function isBashEventStdout(e: BashEvent): e is BashEventStdout { return e.type === 'stdout'; }
export function isBashEventStderr(e: BashEvent): e is BashEventStderr { return e.type === 'stderr'; }
export function isBashEventExit(e: BashEvent): e is BashEventExit { return e.type === 'exit'; }
