// Auto-generated by hub-codegen
// Do not edit manually

/** Summary of a child plugin */
export interface ChildSummary {
  /** Human-readable description */
  description: string;
  /** Content hash for cache invalidation */
  hash: string;
  /** The child's namespace */
  namespace: string;
}

/** Current health status */
export interface HealthEventStatus {
  type: 'status';
  status: string;
  timestamp: number;
  uptimeSeconds: number;
}

/** Stream events from health check */
export type HealthEvent = HealthEventStatus;

export function isHealthEventStatus(e: HealthEvent): e is HealthEventStatus { return e.type === 'status'; }

/** Schema for a single method exposed by a plugin */
export interface MethodSchema {
  /** Whether this method supports bidirectional communication

When true, the server can send requests to the client during method execution
and wait for responses (e.g., confirmations, prompts, selections). */
  bidirectional?: boolean;
  /** Human-readable description of what this method does */
  description: string;
  /** Content hash of the method definition (for cache invalidation)
Generated by hashing the method signature within hub-macro */
  hash: string;
  /** Method name (e.g., "echo", "check") */
  name: string;
  /** JSON Schema for the method's parameters (None if no params) */
  params?: Schema | null;
  /** JSON Schema for the request type sent from server to client

Only relevant when `bidirectional: true`. Describes the structure of
requests the server may send during method execution. */
  requestType?: Schema | null;
  /** JSON Schema for the response type sent from client to server

Only relevant when `bidirectional: true`. Describes the structure of
responses the client should send in reply to server requests. */
  responseType?: Schema | null;
  /** JSON Schema for the method's return type (None if not specified) */
  returns?: Schema | null;
  /** Whether this method streams multiple events (true) or returns a single result (false)

- `streaming: true` → returns `AsyncGenerator<T>` (multiple events)
- `streaming: false` → returns `Promise<T>` (single event, collected)

All methods use the same streaming protocol under the hood, but this flag
tells clients how to present the result. */
  streaming?: boolean;
}

/** A plugin's schema with methods and child summaries.

Children are represented as summaries (namespace, description, hash) rather
than full recursive schemas. This enables lazy traversal - clients can fetch
child schemas individually via `{namespace}.schema`.

- Leaf plugins have `children = None`
- Hub plugins have `children = Some([ChildSummary, ...])` */
export interface PluginSchema {
  /** Child plugin summaries (None = leaf plugin, Some = hub plugin) */
  children?: unknown[] | null;
  /** Hash of ONLY child plugin hashes (None for leaf plugins)
Changes when any child's hash changes (recursively) */
  childrenHash?: string | null;
  /** Short description of the plugin (max 15 words) */
  description: string;
  /** Composite hash = hash(self_hash + children_hash)
Use this if you want a single hash for the entire subtree
Backward compatible with previous single-hash system */
  hash: string;
  /** Detailed description of the plugin (optional) */
  longDescription?: string | null;
  /** Methods exposed by this plugin */
  methods: MethodSchema[];
  /** The plugin's namespace (e.g., "echo", "plexus") */
  namespace: string;
  /** Hash of ONLY this plugin's methods (ignores children)
Changes when method signatures, names, or descriptions change */
  selfHash: string;
  /** The plugin's version (e.g., "1.0.0") */
  version: string;
}

export type Schema = unknown;

// === Stub Types (referenced but not defined in schema) ===

/** Stub type - definition missing from IR */
export type SchemaResult = unknown;
