// Auto-generated by hub-codegen
// Do not edit manually

import type { UUID } from '../cone/types';

export interface ArborEventTreeCreated {
  type: 'tree_created';
  treeId: UUID;
}

export interface ArborEventTreeDeleted {
  type: 'tree_deleted';
  treeId: UUID;
}

export interface ArborEventTreeUpdated {
  type: 'tree_updated';
  treeId: UUID;
}

export interface ArborEventTreeList {
  type: 'tree_list';
  treeIds: UUID[];
}

export interface ArborEventTreeClaimed {
  type: 'tree_claimed';
  newCount: number;
  ownerId: string;
  treeId: UUID;
}

export interface ArborEventTreeReleased {
  type: 'tree_released';
  newCount: number;
  ownerId: string;
  treeId: UUID;
}

export interface ArborEventTreeScheduledDeletion {
  type: 'tree_scheduled_deletion';
  scheduledAt: number;
  treeId: UUID;
}

export interface ArborEventTreeArchived {
  type: 'tree_archived';
  archivedAt: number;
  treeId: UUID;
}

export interface ArborEventTreeRefs {
  type: 'tree_refs';
  refs: ResourceRefs;
  treeId: UUID;
}

export interface ArborEventNodeCreated {
  type: 'node_created';
  nodeId: UUID;
  parent: UUID | null;
  treeId: UUID;
}

export interface ArborEventNodeUpdated {
  type: 'node_updated';
  newId: UUID;
  oldId: UUID;
  treeId: UUID;
}

export interface ArborEventNodeDeleted {
  type: 'node_deleted';
  nodeId: UUID;
  treeId: UUID;
}

export interface ArborEventNodeClaimed {
  type: 'node_claimed';
  newCount: number;
  nodeId: UUID;
  ownerId: string;
  treeId: UUID;
}

export interface ArborEventNodeReleased {
  type: 'node_released';
  newCount: number;
  nodeId: UUID;
  ownerId: string;
  treeId: UUID;
}

export interface ArborEventNodeScheduledDeletion {
  type: 'node_scheduled_deletion';
  nodeId: UUID;
  scheduledAt: number;
  treeId: UUID;
}

export interface ArborEventNodeArchived {
  type: 'node_archived';
  archivedAt: number;
  nodeId: UUID;
  treeId: UUID;
}

export interface ArborEventNodeRefs {
  type: 'node_refs';
  nodeId: UUID;
  refs: ResourceRefs;
  treeId: UUID;
}

export interface ArborEventTreeData {
  type: 'tree_data';
  tree: Tree;
}

export interface ArborEventTreeSkeleton {
  type: 'tree_skeleton';
  skeleton: TreeSkeleton;
}

export interface ArborEventNodeData {
  type: 'node_data';
  node: Node;
  treeId: UUID;
}

export interface ArborEventNodeChildren {
  type: 'node_children';
  children: UUID[];
  nodeId: UUID;
  treeId: UUID;
}

export interface ArborEventNodeParent {
  type: 'node_parent';
  nodeId: UUID;
  parent: UUID | null;
  treeId: UUID;
}

export interface ArborEventContextPath {
  type: 'context_path';
  path: UUID[];
  treeId: UUID;
}

export interface ArborEventContextPathData {
  type: 'context_path_data';
  nodes: Node[];
  treeId: UUID;
}

export interface ArborEventContextHandles {
  type: 'context_handles';
  handles: Handle[];
  treeId: UUID;
}

export interface ArborEventContextLeaves {
  type: 'context_leaves';
  leaves: UUID[];
  treeId: UUID;
}

export interface ArborEventTreesScheduled {
  type: 'trees_scheduled';
  treeIds: UUID[];
}

export interface ArborEventNodesScheduled {
  type: 'nodes_scheduled';
  nodeIds: UUID[];
  treeId: UUID;
}

export interface ArborEventTreesArchived {
  type: 'trees_archived';
  treeIds: UUID[];
}

export interface ArborEventTreeRender {
  type: 'tree_render';
  render: string;
  treeId: UUID;
}

export interface ArborEventViewCreated {
  type: 'view_created';
  sourceTreeId: UUID;
  viewTreeId: UUID;
}

export interface ArborEventRangeAdded {
  type: 'range_added';
  rangeNodeId: UUID;
  viewTreeId: UUID;
}

export interface ArborEventTextRunsDetected {
  type: 'text_runs_detected';
  runs: TextRun[];
  treeId: UUID;
}

export interface ArborEventViewCollapsed {
  type: 'view_collapsed';
  collapsedRuns: TextRun[];
  sourceTreeId: UUID;
  viewTreeId: UUID;
}

export interface ArborEventRangeContent {
  type: 'range_content';
  content: RangeContent;
  endNode: UUID;
  startNode: UUID;
  treeId: UUID;
}

export interface ArborEventError {
  type: 'error';
  message: string;
}

/** Events emitted by Arbor operations */
export type ArborEvent = ArborEventTreeCreated | ArborEventTreeDeleted | ArborEventTreeUpdated | ArborEventTreeList | ArborEventTreeClaimed | ArborEventTreeReleased | ArborEventTreeScheduledDeletion | ArborEventTreeArchived | ArborEventTreeRefs | ArborEventNodeCreated | ArborEventNodeUpdated | ArborEventNodeDeleted | ArborEventNodeClaimed | ArborEventNodeReleased | ArborEventNodeScheduledDeletion | ArborEventNodeArchived | ArborEventNodeRefs | ArborEventTreeData | ArborEventTreeSkeleton | ArborEventNodeData | ArborEventNodeChildren | ArborEventNodeParent | ArborEventContextPath | ArborEventContextPathData | ArborEventContextHandles | ArborEventContextLeaves | ArborEventTreesScheduled | ArborEventNodesScheduled | ArborEventTreesArchived | ArborEventTreeRender | ArborEventViewCreated | ArborEventRangeAdded | ArborEventTextRunsDetected | ArborEventViewCollapsed | ArborEventRangeContent | ArborEventError;

export function isArborEventTreeCreated(e: ArborEvent): e is ArborEventTreeCreated { return e.type === 'tree_created'; }
export function isArborEventTreeDeleted(e: ArborEvent): e is ArborEventTreeDeleted { return e.type === 'tree_deleted'; }
export function isArborEventTreeUpdated(e: ArborEvent): e is ArborEventTreeUpdated { return e.type === 'tree_updated'; }
export function isArborEventTreeList(e: ArborEvent): e is ArborEventTreeList { return e.type === 'tree_list'; }
export function isArborEventTreeClaimed(e: ArborEvent): e is ArborEventTreeClaimed { return e.type === 'tree_claimed'; }
export function isArborEventTreeReleased(e: ArborEvent): e is ArborEventTreeReleased { return e.type === 'tree_released'; }
export function isArborEventTreeScheduledDeletion(e: ArborEvent): e is ArborEventTreeScheduledDeletion { return e.type === 'tree_scheduled_deletion'; }
export function isArborEventTreeArchived(e: ArborEvent): e is ArborEventTreeArchived { return e.type === 'tree_archived'; }
export function isArborEventTreeRefs(e: ArborEvent): e is ArborEventTreeRefs { return e.type === 'tree_refs'; }
export function isArborEventNodeCreated(e: ArborEvent): e is ArborEventNodeCreated { return e.type === 'node_created'; }
export function isArborEventNodeUpdated(e: ArborEvent): e is ArborEventNodeUpdated { return e.type === 'node_updated'; }
export function isArborEventNodeDeleted(e: ArborEvent): e is ArborEventNodeDeleted { return e.type === 'node_deleted'; }
export function isArborEventNodeClaimed(e: ArborEvent): e is ArborEventNodeClaimed { return e.type === 'node_claimed'; }
export function isArborEventNodeReleased(e: ArborEvent): e is ArborEventNodeReleased { return e.type === 'node_released'; }
export function isArborEventNodeScheduledDeletion(e: ArborEvent): e is ArborEventNodeScheduledDeletion { return e.type === 'node_scheduled_deletion'; }
export function isArborEventNodeArchived(e: ArborEvent): e is ArborEventNodeArchived { return e.type === 'node_archived'; }
export function isArborEventNodeRefs(e: ArborEvent): e is ArborEventNodeRefs { return e.type === 'node_refs'; }
export function isArborEventTreeData(e: ArborEvent): e is ArborEventTreeData { return e.type === 'tree_data'; }
export function isArborEventTreeSkeleton(e: ArborEvent): e is ArborEventTreeSkeleton { return e.type === 'tree_skeleton'; }
export function isArborEventNodeData(e: ArborEvent): e is ArborEventNodeData { return e.type === 'node_data'; }
export function isArborEventNodeChildren(e: ArborEvent): e is ArborEventNodeChildren { return e.type === 'node_children'; }
export function isArborEventNodeParent(e: ArborEvent): e is ArborEventNodeParent { return e.type === 'node_parent'; }
export function isArborEventContextPath(e: ArborEvent): e is ArborEventContextPath { return e.type === 'context_path'; }
export function isArborEventContextPathData(e: ArborEvent): e is ArborEventContextPathData { return e.type === 'context_path_data'; }
export function isArborEventContextHandles(e: ArborEvent): e is ArborEventContextHandles { return e.type === 'context_handles'; }
export function isArborEventContextLeaves(e: ArborEvent): e is ArborEventContextLeaves { return e.type === 'context_leaves'; }
export function isArborEventTreesScheduled(e: ArborEvent): e is ArborEventTreesScheduled { return e.type === 'trees_scheduled'; }
export function isArborEventNodesScheduled(e: ArborEvent): e is ArborEventNodesScheduled { return e.type === 'nodes_scheduled'; }
export function isArborEventTreesArchived(e: ArborEvent): e is ArborEventTreesArchived { return e.type === 'trees_archived'; }
export function isArborEventTreeRender(e: ArborEvent): e is ArborEventTreeRender { return e.type === 'tree_render'; }
export function isArborEventViewCreated(e: ArborEvent): e is ArborEventViewCreated { return e.type === 'view_created'; }
export function isArborEventRangeAdded(e: ArborEvent): e is ArborEventRangeAdded { return e.type === 'range_added'; }
export function isArborEventTextRunsDetected(e: ArborEvent): e is ArborEventTextRunsDetected { return e.type === 'text_runs_detected'; }
export function isArborEventViewCollapsed(e: ArborEvent): e is ArborEventViewCollapsed { return e.type === 'view_collapsed'; }
export function isArborEventRangeContent(e: ArborEvent): e is ArborEventRangeContent { return e.type === 'range_content'; }
export function isArborEventError(e: ArborEvent): e is ArborEventError { return e.type === 'error'; }

/** Handle pointing to external data with versioning

Display format: `{plugin_id}@{version}::{method}:meta[0]:meta[1]:...`

Examples:
- `550e8400-e29b-41d4-a716-446655440000@1.0.0::chat:msg-123:user:bob`
- `123e4567-e89b-12d3-a456-426614174000@1.0.0::execute:cmd-789` */
export interface Handle {
  /** Metadata parts - variable length list of strings
For messages: typically [message_uuid, role, optional_extra...] */
  meta?: string[];
  /** Creation method that produced this handle (e.g., "chat", "execute") */
  method: string;
  /** Stable plugin instance identifier (UUID) */
  pluginId: string;
  /** Plugin version (semantic version: "MAJOR.MINOR.PATCH")
Used for schema/type lookup */
  version: string;
}

/** A node in the conversation tree */
export interface Node {
  /** Archived timestamp (Unix seconds) */
  archivedAt?: number | null;
  /** Child nodes (in order) */
  children: UUID[];
  /** Creation timestamp (Unix seconds) */
  createdAt: number;
  /** Node data (handle or built-in) */
  data: NodeType;
  /** Unique identifier for this node */
  id: UUID;
  /** Optional metadata */
  metadata?: unknown;
  /** Parent node (None for root) */
  parent?: UUID | null;
  /** Reference count information */
  refs?: ResourceRefs | null;
  /** Scheduled deletion timestamp (Unix seconds) */
  scheduledDeletionAt?: number | null;
  /** Reference counting state */
  state?: ResourceState | null;
}

/** Lightweight node representation (just structure, no data) */
export interface NodeSkeleton {
  children: UUID[];
  id: UUID;
  /** Type indicator (but not the actual data) */
  nodeType: string;
  parent?: UUID | null;
}

/** Built-in text node (data stored in Arbor) */
export interface NodeTypeText {
  type: 'text';
  content: string;
}

/** External data reference */
export interface NodeTypeExternal {
  type: 'external';
  handle: Handle;
}

/** Node type discriminator */
export type NodeType = NodeTypeText | NodeTypeExternal;

export function isNodeTypeText(e: NodeType): e is NodeTypeText { return e.type === 'text'; }
export function isNodeTypeExternal(e: NodeType): e is NodeTypeExternal { return e.type === 'external'; }

/** Merged text content */
export interface RangeContentText {
  type: 'text';
  content: string;
  nodeCount: number;
  nodeIds: UUID[];
}

/** Structure reference (placeholder) */
export interface RangeContentReference {
  type: 'reference';
  endNode: UUID;
  nodeCount: number;
  startNode: UUID;
  treeId: UUID;
}

/** Custom collapse strategy */
export interface RangeContentCustom {
  type: 'custom';
  metadata: unknown;
  nodeCount: number;
  strategy: string;
}

/** Result of resolving a range */
export type RangeContent = RangeContentText | RangeContentReference | RangeContentCustom;

export function isRangeContentText(e: RangeContent): e is RangeContentText { return e.type === 'text'; }
export function isRangeContentReference(e: RangeContent): e is RangeContentReference { return e.type === 'reference'; }
export function isRangeContentCustom(e: RangeContent): e is RangeContentCustom { return e.type === 'custom'; }

/** Reference counting information for a resource */
export interface ResourceRefs {
  /** Who owns references (owner_id -> count) */
  owners: Record<string, unknown>;
  /** Total reference count */
  refCount: number;
}

/** Resource state in deletion lifecycle */
export type ResourceState = "active" | "scheduled_delete" | "archived";

/** Result of analyzing text runs in a tree */
export interface TextRun {
  /** Total character count */
  charCount: number;
  /** Last node in the run */
  endNode: UUID;
  /** Number of nodes in the run */
  length: number;
  /** First node in the run */
  startNode: UUID;
}

/** A conversation tree */
export interface Tree {
  /** Archived timestamp (Unix seconds) */
  archivedAt?: number | null;
  /** Creation timestamp (Unix seconds) */
  createdAt: number;
  /** Unique identifier for this tree */
  id: UUID;
  /** Optional tree-level metadata (name, description, etc.) */
  metadata?: unknown;
  /** All nodes in the tree (NodeId -> Node) */
  nodes: Record<string, unknown>;
  /** Reference count information */
  refs?: ResourceRefs | null;
  /** Root node ID */
  root: UUID;
  /** Scheduled deletion timestamp (Unix seconds) */
  scheduledDeletionAt?: number | null;
  /** Reference counting state */
  state?: ResourceState | null;
  /** Last modified timestamp (Unix seconds) */
  updatedAt: number;
}

/** Lightweight tree structure */
export interface TreeSkeleton {
  id: UUID;
  nodes: Record<string, unknown>;
  root: UUID;
  state?: ResourceState | null;
}
